import type { Metadata } from "next";
import Navbar from "~/components/Navbar";

import "./globals.scss";
import Footer from "~/components/Footer";
import ScrollToTop from "~/components/ScrollToTop";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className="min-h-screen">{children}</main>
        <ScrollToTop />
        <Footer />
      </body>
    </html>
  );
}
